version: 1

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      # - darwin
    ldflags: -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

changelog:
  disable: true