version: '3'

tasks:
  test:
    desc: Run tests with go test
    cmd: go test -v ./...
  test-no-cache:
    desc: Run tests with go test
    cmd: go test -v -count=1 ./...
  update-golden-test:
    desc: Update golden testing results
    cmd: go test -update -clean ./... -clean
  build:
    cmd: CGO_ENABLED=0 go build -o forge .
  get-disassembler:
    desc: Update docker-image-disassembler imports (required while it is private repository)
    env:
      GOPRIVATE: github.com/tklab-group
    cmds: 
      - go get github.com/tklab-group/docker-image-disassembler@main
      - go mod tidy